### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by vardumper** [Family-Office-Company/FamilyOfficeFixtures#1]
Rather than adding the couple of classes to my own namespace, I tried installing this with composer.
First I added this to the `repositories` section:
```
{
  "type" : "vcs",
  "url" : "git@github.com:Family-Office-Company/FamilyOfficeFixtures.git"
},
```
and then ran composer: `composer require family-office/fixtures:dev-main --ignore-platform-reqs`.
Unfortunately I am getting two problems:

```
 Problem 1
    - vimeo/psalm[4.9.0, ..., 4.9.3] require nikic/php-parser ^4.12 -> found nikic/php-parser[v4.12.0] but it conflicts with your root composer.json require (~4.10.4).
    - family-office/fixtures dev-main requires vimeo/psalm ^4.9 -> satisfiable by vimeo/psalm[4.9.0, 4.9.1, 4.9.2, 4.9.3].
    - Root composer.json requires family-office/fixtures dev-main -> satisfiable by family-office/fixtures[dev-main].
```

and I get this output for `composer why nikic/php-parser`

```
shopware/production                 dev-master   requires (for development)  nikic/php-parser (~4.10.4)  
frosh/frosh-platform-template-mail  9999999-dev  requires                    nikic/php-parser (*)        
phpunit/php-code-coverage           9.2.6        requires                    nikic/php-parser (^4.10.2)  
sebastian/complexity                2.0.2        requires                    nikic/php-parser (^4.7)     
sebastian/lines-of-code             1.0.3        requires                    nikic/php-parser (^4.6)  
```

Any idea how to get this installed via composer?

**Comment by vardumper** [comment]
Nevermind. I just had to change my composer.json's dev section. This has been an outdated Shopware production template...

**Comment by vardumper** [comment]
maybe a couple of lines of install instructions would be a great addition to the readme.
* add repository
* require package
* `bin/console plugin:refresh && bin/console plugin:install FamilyOfficeFixtures --activate`

**Comment by bpesch** [comment]
Hello Erik,
thank you very much for your feedback!

- I [moved](https://github.com/Family-Office-Company/FamilyOfficeFixtures/commit/7eebc7f7f74612e3d45604afbe22289065dd42ef) the dev dependencies to the correct section within the composer.json
- The package was [released](https://github.com/Family-Office-Company/FamilyOfficeFixtures/releases/tag/1.0.0) on [Packagist](https://packagist.org/packages/family-office/fixtures). So you won't need to manually set the repository anymore.
- [Installation instructions](https://github.com/Family-Office-Company/FamilyOfficeFixtures/commit/974176440aba62d694a564a35587f85a07e411e2) were added to the README

Please let me know if you're satisfied!
