### ISSUE TITLE
Priorities?

### ISSUE THREAD

**Issue by vardumper** [Family-Office-Company/FamilyOfficeFixtures#2]
Is there a way without additional code to control the order of Fixture execution?
Let's say, before creating ElephantFixtures, I need to create EarSize or Sex Fixtures. Can I control that with the order in services.xml/yaml?

**Comment by bpesch** [comment]
Hello @vardumper,
thank you for your feedback!

I have added a dependency feature and changed the documentation accordingly. (See PR mentioning this issue)
The new version will be released soon.

**Comment by bpesch** [comment]
The new version was tagged as `1.1.0` and released.

**Comment by vardumper** [comment]
Pretty cool! Thanks, that was really fast.
